spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    change-log: classpath:db/database.xml
    contexts: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sincronizacao-receita
    username: user
    password: pass
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: validate
      
file:
  source: C:\Users\charl\data\in\accounts.csv
  output: C:\Users\charl\data\out\accounts.csv
